# Chapter 5 - Basic Math and Statistics
## Segment 2 - Multiplying matrices and basic linear algebra

In [1]:
import numpy as np
from numpy.random import randn

In [2]:
# set decimals returned to 2
np.set_printoptions(precision = 2)

## Multiplying matricies and basic linear algebra

In [3]:
# create matrices
aa = np.array([[2,3,6],[1,3,5],[10,20,30]])
aa

array([[ 2,  3,  6],
       [ 1,  3,  5],
       [10, 20, 30]])

In [4]:
bb = np.array([[0,1,2],[3,4,5],[6,7,8]])
bb

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [5]:
# multiply aa by bb
aa*bb

array([[  0,   3,  12],
       [  3,  12,  25],
       [ 60, 140, 240]])

In [6]:
## dot product of aa and bb
np.dot(aa,bb)

array([[ 45,  56,  67],
       [ 39,  48,  57],
       [240, 300, 360]])