# Chapter 5 - Basic Math and Statistics
## Segment 10 - Quiz

In [1]:
import pandas as pd
import numpy as np

In [2]:
# address of data 
address = '~/Desktop/2022/python-ds-essentials/2_data/mtcars.csv'
# call address
cars = pd.read_csv(address)
# name columns
cars.columns = ['car_names', 'mpg', 'cyl', 'disp', 'hp', 'drat', 'wt', 'qsec', 'vs', 'am', 'gear', 'carb']

In [6]:
cars['qsec'].mean()

17.848750000000003

In [7]:
a=np.array([[1,3],[2,4]])
b=np.array(([5,8],[7,9]))
a*b

array([[ 5, 24],
       [14, 36]])

In [8]:
x=np.array([1,2,7])
y=np.array([3,8,9])
np.dot(x,y)

82

In [10]:
a=np.array([[7,9],[5,12]])
b=np.array(([2,8],[7,4]))
np.dot(a,b)

array([[77, 92],
       [94, 88]])

In [11]:
a=np.array([[1,2,3],[4,5,6]])
b=np.array(([10,11],[20,21],[30,31]))
np.dot(a,b)

array([[140, 146],
       [320, 335]])

In [13]:
a=np.array([1,8,2,6,3,8,5,5,5,5])
b=np.array([17,16,20,18,22,15,21,15,17,22])
(a+b)/10

array([1.8, 2.4, 2.2, 2.4, 2.5, 2.3, 2.6, 2. , 2.2, 2.7])

In [16]:
a=np.array([10,15,20])
b=np.array([5,7,9])
(a-b)*7

array([35, 56, 77])